
services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   networks:
  #     - pongnet
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs:rw
  #     - ./vhost.d:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html

  # nginx-proxy-letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: nginx-proxy-letsencrypt
  #   networks:
  #     - pongnet
  #   depends_on:
  #     - nginx-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./certs:/etc/nginx/certs:rw
  #     - ./vhost.d:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html

  front:
    container_name: front
    build:
      context: ./front
    image: front
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - pongnet
    volumes:
    - ./front/src:/usr/share/nginx/html
    # environment:
    #   - VIRTUAL_HOST=jgravalo.42.fr
    #   - LETSENCRYPT_HOST=jgravalo.42.fr
    #   - LETSENCRYPT_EMAIL=jgravalo@student.42barcelona.com

  back:
    container_name: back
    build:
      context: ./back
    image: back
    ports:
      - "8000:8000"
    # environment:
    #   DATABASE_URL: "postgres://postgres:Jesus20022@db:5432/postgres"
    # depends_on:
    #   - db
    networks:
      - pongnet

  # db:
  #   image: postgres:15
  #   container_name: db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Jesus20022
  #     POSTGRES_DB: postgres
  #   networks:
  #     - pongnet
  #   ports:
  #     - "5432:5432"

networks:
  pongnet:
    driver: bridge