services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   networks:
  #     - pongnet
  #   ports:
  #     - "8080:80"
  #     - "8443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./certs:/etc/nginx/certs:rw
  #     - ./vhost.d:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html

  # nginx-proxy-letsencrypt:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: nginx-proxy-letsencrypt
  #   networks:
  #     - pongnet
  #   depends_on:
  #     - nginx-proxy
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./certs:/etc/nginx/certs:rw
  #     - ./vhost.d:/etc/nginx/vhost.d
  #     - ./html:/usr/share/nginx/html

  front:
    container_name: front
    build:
      context: ./front
    image: front
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - pongnet
    volumes:
    - ./front/src:/usr/share/nginx/html
    # environment:
    #   - VIRTUAL_HOST=jgravalo.42.fr
    #   - LETSENCRYPT_HOST=jgravalo.42.fr
    #   - LETSENCRYPT_EMAIL=jgravalo@student.42barcelona.com

  back:
    container_name: back
    build:
      context: ./back
    image: back
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=Jesus20022
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pongnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: db
    build:
      context: ./db
    container_name: db
    networks:
      - pongnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    name: pgdata

networks:
  pongnet:
    name: pongnet
    driver: bridge
