networks:
  jgravalo-pongnet:
    name: jgravalo-pongnet
    driver: bridge

services:
  front:
    container_name: front
    build:
      context: ./front
    image: front
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - jgravalo-pongnet

  back:
    container_name: back
    build:
      context: ./back
    image: back
    ports:
      - "8000:8000"
    networks:
      - jgravalo-pongnet

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: jgravalo
      POSTGRES_PASSWORD: Jesus20022
      POSTGRES_DB: 42Pong
    networks:
      - jgravalo-pongnet