
services:
  front:
    container_name: front
    build:
      context: ./front
    image: front
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - pongnet

  back:
    container_name: back
    build:
      context: ./back
    image: back
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://jgravalo:Jesus20022@db:5432/42Pong"
    depends_on:
      - db
    networks:
      - pongnet

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: jgravalo
      POSTGRES_PASSWORD: Jesus20022
      POSTGRES_DB: 42Pong
    networks:
      - pongnet
    ports:
      - "5432:5432"

networks:
  pongnet:
    driver: bridge