global:
  scrape_interval: 15s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['back:8000']

  - job_name: 'database'
    static_configs:
      - targets: ['db-exporter:9187']
  
  - job_name: 'proxy'
    static_configs:
      - targets: ['waf-exporter:9113']

  - job_name: 'vault'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['vault:8200']
    authorization:
      credentials: "$VAULT_TOKEN"

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

rule_files:
  - "/etc/prometheus/alerting.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]