global:
  scrape_interval: 15s       # How often Prometheus scrapes metrics
  evaluation_interval: 15s   # How often rules (alerts) are evaluated

scrape_configs:
  - job_name: 'django_backend'
    static_configs:
      - targets: ['back:8000']
    # If your metrics endpoint is not the default "/metrics", you can add:
    # metrics_path: "/metrics"