global:
  scrape_interval: 15s       # How often Prometheus scrapes metrics
  evaluation_interval: 15s   # How often rules (alerts) are evaluated

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['back:8000']
  - job_name: 'database'
    static_configs:
      - targets: ['db:9187']