{
 "title": "Nginx Web server",
 "tags": [
  "nginx",
  "http",
  "waf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "24h Upime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(nginx_up[24h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Requests per Connection",
   "type": "gauge",
   "description": "Measures server efficiency.\nIf too low, keep-alive might not be working properly.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" },
    { "expr": "nginx_connections_accepted", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Uptime",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "avg_over_time(nginx_up[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests Served",
   "type": "timeseries",
   "description": "Helps detect abnormal traffic (e.g., DDoS).\nTracks total HTTP requests handled over time.\nUseful for long-term traffic growth analysis.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "barchart",
   "description": "Show real-time traffic intensity. Helps spot traffic spikes (potential DDoS or high user load).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active vs. Waiting connections",
   "type": "timeseries",
   "description": "Show how many connections are actively being processed vs. just waiting.Helps detect server overload (if waiting connections are too high).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active Connections" },
    { "expr": "nginx_connections_waiting", "legendFormat": "Waiting Connections" }
   ]
  }
 ]
}