{
 "title": "HCP Vault",
 "description": " Hashicorp Vault Metrics",
 "tags": [
  "vault",
  "hcp"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster:", "query": { "query": "label_values(cluster_id)" } },
   {
    "name": "project",
    "query": {
     "query": "label_values(vault_runtime_alloc_bytes{cluster_id=\"$cluster\"}, project_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{cluster_id=\"$cluster\"})",
     "legendFormat": "$cluster"
    }
   ]
  },
  {
   "title": "Active Leases",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Identity Entities by Namespace",
   "type": "table",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "avg by (namespace) (vault_identity_entity_count{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "KV Secrets by Mount",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(mount_point) (vault_secret_kv_count{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Auth Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (irate(vault_core_handle_login_request{cluster_id=\"$cluster\"}[1m])) by (cluster_id)"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (cluster_id) ((1-irate(host_cpu_seconds_total{mode=\"idle\",cluster_id=\"$cluster\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(host_filesystem_total_bytes{cluster_id=\"$cluster\"}) - sum(host_filesystem_free_bytes{cluster_id=\"$cluster\"})) / sum(host_filesystem_total_bytes{cluster_id=\"$cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(host_memory_total_bytes{cluster_id=\"$cluster\"}) - sum(host_memory_available_bytes{cluster_id=\"$cluster\"})) / sum(host_memory_total_bytes{cluster_id=\"$cluster\"}) * 100"
    }
   ]
  },
  { "title": "Token", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_token_count{cluster_id=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Available Tokens by Policy",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_token_count_by_policy{cluster_id=\"$cluster\"}",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Available Tokens by TTL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_token_count_by_ttl{cluster_id=\"$cluster\"}",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_token_count_by_auth{cluster_id=\"$cluster\"}",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Batch and Service Tokens by Methods & TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(auth_method, creation_ttl) (vault_token_creation{cluster_id=\"$cluster\"})",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count{cluster_id=\"$cluster\"}[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  {
   "title": "Token Revoke Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg(vault_expire_revoke{cluster_id=\"$cluster\"}) by (cluster_id)"
    }
   ]
  },
  {
   "title": "Token Renew Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg(vault_expire_renew{cluster_id=\"$cluster\"}) by (cluster_id)"
    }
   ]
  }
 ]
}