name: Deploy on Remote Server

#Trigger deployment when main branch is updated (push event)
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 52.0.118.59
          username: ec2-user
          key: ${{ secrets.AWS_Private }}
          script: |
            cd /home/ec2-user/ft_transcendence
            git checkout main
            git reset --hard
            git clean -fd
            git pull --ff-only
            make all ENVIRONMENT=production